# Generated by Django 4.0.6 on 2022-08-09 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=20, null=True)),
                ('school_address', models.TextField(null=True)),
                ('school_email', models.EmailField(max_length=20, null=True)),
                ('location', models.CharField(max_length=15, null=True)),
                ('contact', models.IntegerField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, null=True)),
                ('last_name', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=20, null=True)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('P', 'Prefer not to say')], max_length=2, null=True)),
                ('address', models.TextField(null=True)),
                ('stream', models.CharField(choices=[('A', 'Adalab'), ('An', 'Annita B'), ('H', 'Hopper Lab')], max_length=2, null=True)),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('admission_number', models.IntegerField(null=True)),
                ('phone_number', models.IntegerField(max_length=15, null=True)),
                ('emergency_contact', models.IntegerField(max_length=15, null=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Student_School', to='SchoolSystem.school')),
            ],
        ),
    ]
