# Generated by Django 4.0.6 on 2022-08-09 10:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField(null=True)),
                ('balance', models.IntegerField(null=True)),
                ('receipt_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15, null=True)),
                ('lastname', models.CharField(max_length=15, null=True)),
                ('unit_specialty', models.CharField(choices=[('PY', 'Python'), ('KO', 'Kotlin'), ('FR', 'Frontendweb'), ('IOT', 'IOT'), ('UX', 'UserResearch'), ('UI', 'UI/UX Design'), ('PD', 'Professiondevelopment'), ('NYJ', 'Navigating Your Journey')], max_length=11, null=True)),
                ('contact', models.IntegerField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=20, null=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Teacher_School', to='SchoolSystem.school')),
            ],
        ),
        migrations.CreateModel(
            name='StudentId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StudentId_Student', to='SchoolSystem.student')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15, null=True)),
                ('lastname', models.CharField(max_length=15, null=True)),
                ('unit_specialty', models.CharField(choices=[('CH', 'Chef'), ('CK', 'Cook'), ('Gt', 'Gate_Keeper'), ('GARDER', 'Gardener'), ('MT', 'Matron'), ('AC', 'Accountant'), ('NU', 'Nurse'), ('CODEHIVE', 'CodeHive Lead')], max_length=10, null=True)),
                ('contact', models.IntegerField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=20, null=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Staff_School', to='SchoolSystem.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_fees', models.IntegerField(null=True)),
                ('amount_paid', models.IntegerField(null=True)),
                ('balance', models.IntegerField(null=True)),
                ('receipt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SchoolFees_Receipt', to='SchoolSystem.receipt')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SchoolFees_Student', to='SchoolSystem.student')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=25, null=True)),
                ('account_number', models.IntegerField(max_length=30, null=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SchoolAccount_School', to='SchoolSystem.school')),
            ],
        ),
        migrations.AddField(
            model_name='receipt',
            name='school_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Receipt_SchoolAccount', to='SchoolSystem.schoolaccount'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Receipt_Student', to='SchoolSystem.student'),
        ),
        migrations.CreateModel(
            name='LibraryManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LibraryManagement_Student', to='SchoolSystem.student')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AcademicAnalysis_Student', to='SchoolSystem.student')),
            ],
        ),
    ]
