# Generated by Django 4.0.6 on 2022-08-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0003_rename_unit_specialty_staff_occupation_specialty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
