# Generated by Django 4.1 on 2022-08-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0005_alter_student_gender_alter_student_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='work_period',
            field=models.CharField(choices=[('1 Year', '1 Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('4 Years', '4 Years'), ('5 Years', '5 Years')], max_length=22, null=True),
        ),
    ]
