# Generated by Django 4.1 on 2022-08-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0007_alter_staff_email_alter_staff_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='occupation_specialty',
            field=models.CharField(choices=[('Chef', 'Chef'), ('Cook', 'Cook'), ('Gate keeper', 'Gate Keeper'), ('Gardener', 'Gardener'), ('Matron', 'Matron'), ('Accountant', 'Accountant'), ('Nurse', 'Nurse'), ('CodeHive Lead', 'CodeHive Lead')], max_length=22, null=True),
        ),
    ]
