# Generated by Django 4.1 on 2022-08-29 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0008_alter_staff_occupation_specialty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='occupation_specialty',
            new_name='Specialty',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='work_period',
            new_name='period',
        ),
    ]
