# Generated by Django 4.1 on 2022-08-29 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0010_rename_specialty_staff_occupation_specialty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='work_period',
            new_name='period',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='occupation_specialty',
            new_name='specialty',
        ),
    ]
