# Generated by Django 4.1 on 2022-08-29 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0011_rename_work_period_staff_period_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='period',
            new_name='My_Duration',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='email',
            new_name='My_email',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='gender',
            new_name='My_gender',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='school',
            new_name='My_school',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='contact',
            new_name='Mycontact',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='specialty',
            new_name='specialtys',
        ),
    ]
