# Generated by Django 4.1 on 2022-08-29 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0013_rename_my_duration_staff_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='My_school',
        ),
    ]
