# Generated by Django 4.1 on 2022-08-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0014_remove_staff_my_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='my_address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='my_email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='gender',
            new_name='my_gender',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='stream',
            new_name='my_stream',
        ),
        migrations.RemoveField(
            model_name='student',
            name='admission_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('Uganda', 'Uganda'), ('South Sudan', 'South Sudan'), ('Rwanda', 'Rwanda'), ('Kenya', 'Kenya'), ('Tanzania', 'Tanzania')], max_length=30, null=True),
        ),
    ]
