# Generated by Django 4.0.6 on 2022-09-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0018_alter_student_nationality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('South Sudan', 'South Sudan'), ('Rwanda', 'Rwanda'), ('Uganda', 'Uganda'), ('Tanzania', 'Tanzania'), ('Kenya', 'Kenya')], max_length=30, null=True),
        ),
    ]
