# Generated by Django 4.1 on 2022-09-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0020_alter_student_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('Uganda', 'Uganda'), ('Kenya', 'Kenya'), ('South Sudan', 'South Sudan'), ('Tanzania', 'Tanzania'), ('Rwanda', 'Rwanda')], max_length=30, null=True),
        ),
    ]
