# Generated by Django 4.1 on 2022-09-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0024_alter_student_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('Kenya', 'Kenya'), ('South Sudan', 'South Sudan'), ('Tanzania', 'Tanzania'), ('Rwanda', 'Rwanda'), ('Uganda', 'Uganda')], max_length=30, null=True),
        ),
    ]
