# Generated by Django 4.1 on 2022-09-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0025_alter_student_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('Rwanda', 'Rwanda'), ('Tanzania', 'Tanzania'), ('Uganda', 'Uganda'), ('Kenya', 'Kenya'), ('South Sudan', 'South Sudan')], max_length=30, null=True),
        ),
    ]
