# Generated by Django 4.1 on 2022-09-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0026_alter_student_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('Kenya', 'Kenya'), ('Uganda', 'Uganda'), ('South Sudan', 'South Sudan'), ('Rwanda', 'Rwanda'), ('Tanzania', 'Tanzania')], max_length=30, null=True),
        ),
    ]
