# Generated by Django 4.1 on 2022-09-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0028_alter_student_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('South Sudan', 'South Sudan'), ('Tanzania', 'Tanzania'), ('Rwanda', 'Rwanda'), ('Uganda', 'Uganda'), ('Kenya', 'Kenya')], max_length=30, null=True),
        ),
    ]
