# Generated by Django 4.1 on 2022-10-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0030_alter_student_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('Uganda', 'Uganda'), ('Tanzania', 'Tanzania'), ('South Sudan', 'South Sudan'), ('Rwanda', 'Rwanda'), ('Kenya', 'Kenya')], max_length=30, null=True),
        ),
    ]
