# Generated by Django 4.0.6 on 2022-10-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0032_alter_student_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='guardian_contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('Kenya', 'Kenya'), ('Rwanda', 'Rwanda'), ('South Sudan', 'South Sudan'), ('Tanzania', 'Tanzania'), ('Uganda', 'Uganda')], max_length=30, null=True),
        ),
    ]
