# Generated by Django 4.0.6 on 2022-10-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0033_student_guardian_contact_student_guardian_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_code',
            new_name='laptop_code',
        ),
        migrations.AlterField(
            model_name='student',
            name='my_email',
            field=models.EmailField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('South Sudan', 'South Sudan'), ('Uganda', 'Uganda'), ('Rwanda', 'Rwanda'), ('Tanzania', 'Tanzania'), ('Kenya', 'Kenya')], max_length=30, null=True),
        ),
    ]
