# Generated by Django 4.0.6 on 2022-10-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0034_rename_student_code_student_laptop_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('Kenya', 'Kenya'), ('Uganda', 'Uganda'), ('Tanzania', 'Tanzania'), ('Rwanda', 'Rwanda'), ('South Sudan', 'South Sudan')], max_length=30, null=True),
        ),
    ]
