# Generated by Django 4.0.6 on 2022-10-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0035_alter_student_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='guardian_contact',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='laptop_code',
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('Uganda', 'Uganda'), ('South Sudan', 'South Sudan'), ('Kenya', 'Kenya'), ('Tanzania', 'Tanzania'), ('Rwanda', 'Rwanda')], max_length=30, null=True),
        ),
    ]
