# Generated by Django 4.1 on 2022-10-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0037_alter_student_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('Rwanda', 'Rwanda'), ('Tanzania', 'Tanzania'), ('Uganda', 'Uganda'), ('South Sudan', 'South Sudan'), ('Kenya', 'Kenya')], max_length=30, null=True),
        ),
    ]
