# Generated by Django 4.1 on 2022-10-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0038_alter_student_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('Kenya', 'Kenya'), ('Rwanda', 'Rwanda'), ('South Sudan', 'South Sudan'), ('Tanzania', 'Tanzania'), ('Uganda', 'Uganda')], max_length=30, null=True),
        ),
    ]
