# Generated by Django 4.0.6 on 2022-10-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0041_alter_student_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('Uganda', 'Uganda'), ('South Sudan', 'South Sudan'), ('Tanzania', 'Tanzania'), ('Kenya', 'Kenya'), ('Rwanda', 'Rwanda')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='static/images/profile_picture/'),
        ),
    ]
